heartbeat.interval: 30
heartbeat.delay: 10
heartbeat.topic: "homeassistant/binary_sensor/keeper/state"
ha.restart.command:
system.restart.command:
mqtt.broker:
mqtt.port:
mqtt.user:
mqtt.pass:
mqtt.restart.command: