heartbeat.interval: 30
heartbeat.delay: 10
heartbeat.restart.delay: 180
heartbeat.topic: "homeassistant/binary_sensor/keeper/state"
ha.restart.command: "sudo systemctl restart home-assistant@homeassistant"
system.restart.command: "sudo reboot -f"
mqtt.broker:
mqtt.port:
mqtt.user:
mqtt.pass:
mqtt.restart.command: "sudo systemctl restart mosquitto.service"